name: Build and Push Multi-arch Docker Images

env:
  LATEST_NODE_VERSION: '22'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 20, 18]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            NODE_VERSION=${{ matrix.node-version }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/amplify_pind:node${{ matrix.node-version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/amplify_pind:node${{ matrix.node-version }}-${{ github.sha }}
            ${{ matrix.node-version == env.LATEST_NODE_VERSION && format('{0}/amplify_pind:latest', secrets.DOCKERHUB_USERNAME) || '' }} 